#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-geometry
Version  : 0.3.6
Release  : 2
URL      : https://cran.r-project.org/src/contrib/geometry_0.3-6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/geometry_0.3-6.tar.gz
Summary  : Mesh Generation and Surface Tesselation
Group    : Development/Tools
License  : GPL-3.0 Qhull
Requires: R-geometry-lib
Requires: R-magic
BuildRequires : R-magic
BuildRequires : clr-R-helpers

%description
available in R, in a similar manner as in Octave and MATLAB. Qhull
    computes convex hulls, Delaunay triangulations, halfspace
    intersections about a point, Voronoi diagrams, furthest-site
    Delaunay triangulations, and furthest-site Voronoi diagrams. It
    runs in 2-d, 3-d, 4-d, and higher dimensions. It implements the
    Quickhull algorithm for computing the convex hull. Qhull does not
    support constrained Delaunay triangulations, or mesh generation of
    non-convex objects, but the package does include some R functions
    that allow for this. Currently the package only gives access to
    Delaunay triangulation and convex hull computation.

%package lib
Summary: lib components for the R-geometry package.
Group: Libraries

%description lib
lib components for the R-geometry package.


%prep
%setup -q -c -n geometry

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1521218791

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1521218791
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library geometry
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library geometry
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library geometry
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library geometry|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/geometry/DESCRIPTION
/usr/lib64/R/library/geometry/INDEX
/usr/lib64/R/library/geometry/LICENSE
/usr/lib64/R/library/geometry/Meta/Rd.rds
/usr/lib64/R/library/geometry/Meta/features.rds
/usr/lib64/R/library/geometry/Meta/hsearch.rds
/usr/lib64/R/library/geometry/Meta/links.rds
/usr/lib64/R/library/geometry/Meta/nsInfo.rds
/usr/lib64/R/library/geometry/Meta/package.rds
/usr/lib64/R/library/geometry/NAMESPACE
/usr/lib64/R/library/geometry/NEWS
/usr/lib64/R/library/geometry/R/geometry
/usr/lib64/R/library/geometry/R/geometry.rdb
/usr/lib64/R/library/geometry/R/geometry.rdx
/usr/lib64/R/library/geometry/doc/Announce.txt
/usr/lib64/R/library/geometry/doc/COPYING.txt
/usr/lib64/R/library/geometry/doc/File_id.diz
/usr/lib64/R/library/geometry/doc/MODIFIED.txt
/usr/lib64/R/library/geometry/doc/README.txt
/usr/lib64/R/library/geometry/doc/REGISTER.txt
/usr/lib64/R/library/geometry/doc/html/index.html
/usr/lib64/R/library/geometry/doc/html/qconvex.html
/usr/lib64/R/library/geometry/doc/html/qdelau_f.html
/usr/lib64/R/library/geometry/doc/html/qdelaun.html
/usr/lib64/R/library/geometry/doc/html/qh-code.html
/usr/lib64/R/library/geometry/doc/html/qh-eg.html
/usr/lib64/R/library/geometry/doc/html/qh-faq.html
/usr/lib64/R/library/geometry/doc/html/qh-get.html
/usr/lib64/R/library/geometry/doc/html/qh-impre.html
/usr/lib64/R/library/geometry/doc/html/qh-optc.html
/usr/lib64/R/library/geometry/doc/html/qh-optf.html
/usr/lib64/R/library/geometry/doc/html/qh-optg.html
/usr/lib64/R/library/geometry/doc/html/qh-opto.html
/usr/lib64/R/library/geometry/doc/html/qh-optp.html
/usr/lib64/R/library/geometry/doc/html/qh-optq.html
/usr/lib64/R/library/geometry/doc/html/qh-optt.html
/usr/lib64/R/library/geometry/doc/html/qh-quick.html
/usr/lib64/R/library/geometry/doc/html/qhalf.html
/usr/lib64/R/library/geometry/doc/html/qhull-cpp.xml
/usr/lib64/R/library/geometry/doc/html/qhull.html
/usr/lib64/R/library/geometry/doc/html/qhull.man
/usr/lib64/R/library/geometry/doc/html/qhull.txt
/usr/lib64/R/library/geometry/doc/html/qvoron_f.html
/usr/lib64/R/library/geometry/doc/html/qvoronoi.html
/usr/lib64/R/library/geometry/doc/html/rbox.html
/usr/lib64/R/library/geometry/doc/html/rbox.man
/usr/lib64/R/library/geometry/doc/html/rbox.txt
/usr/lib64/R/library/geometry/doc/index.html
/usr/lib64/R/library/geometry/extdata/ordination.Rdata
/usr/lib64/R/library/geometry/help/AnIndex
/usr/lib64/R/library/geometry/help/aliases.rds
/usr/lib64/R/library/geometry/help/geometry.rdb
/usr/lib64/R/library/geometry/help/geometry.rdx
/usr/lib64/R/library/geometry/help/paths.rds
/usr/lib64/R/library/geometry/html/00Index.html
/usr/lib64/R/library/geometry/html/R.css
/usr/lib64/R/library/geometry/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/geometry/libs/geometry.so
/usr/lib64/R/library/geometry/libs/geometry.so.avx2
/usr/lib64/R/library/geometry/libs/geometry.so.avx512
